{% set name = "dunamai" %}
{% set version = "1.23.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a163746de7ea5acb6dacdab3a6ad621ebc612ed1e528aaa8beedb8887fccd2c4

build:
  number: 0
  noarch: python
  entry_points:
    - dunamai = dunamai.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python {{ python_min }}
  run:
    - packaging >=20.9
    - python >={{ python_min }}

test:
  imports:
    - dunamai
  commands:
    - pip check
    - dunamai --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mtkennerly/dunamai
  summary: Dynamic version generation
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dhirschfeld
    - BastianZim
